### PR TITLE
Add & Update Dependancies

### PR DESCRIPTION
**Pull request by ghost**
Required changes to metro bundle without bugs.

### CODE REVIEW

**Comment by ghost** [comment]
@jasmehar-k Can you check if this runs on your machine?

The code was constantly throwing error messages from the version mismatching packages.

**Comment by ghost** [comment]
The Expo Go app throws an uncaught error about the gesture handler module.

Nothing is thrown on the command line, and the app works normally.

Is this should be okay to ignore?

**Comment by jasmehar-k** [comment]
> The Expo Go app throws an uncaught error about the gesture handler module.
> 
> Nothing is thrown on the command line, and the app works normally.
> 
> Is this should be okay to ignore?

Yeah I think it should be fine

**Comment by jasmehar-k** [comment]
> @jasmehar-k Can you check if this runs on your machine?
> 
> The code was constantly throwing error messages from the version mismatching packages.

Yep works for me. Were the errors about typeScript?

**Pull request closed without merging**
